# 1. Home Assignment

You should work on the assignement in groups of 2 participants. 

Upload your solution as a jupyter notebook to L2P by 13th of June 23:59h. (The deadline is strict)

Do not forget to specify the names of all contributing students in the jupyter notebook.

You should add comments to your code where necessary


By Akash Singh(384008) and Parag Shendye(384146)

# 1. Remove comments
Write a function that takes as input a source a target file name and copies copies all the lines not starting with a # from the source to the target file.

In [24]:
# defining paths for both source and target files
def commentremover(sourcefile,Targetfile):

#open source file as readable and Target file as apendable
    S=open(sourcefile,'r')

    T=open(Targetfile,'a')
    for line in S.readlines():
        if not line.startswith("#"):# this command checks for line not beginning with "#" 
            T.write(line) 
                
#Close both the files                 
    S.close()
    T.close()
        

    

In [25]:
commentremover(sourcefile="C:\\Users\\hp\\Desktop\\edx\\trial_file.txt",Targetfile="C:\\Users\\hp\\Desktop\\edx\\trial_file_4.txt")

# 2. Sudoku
Write a function that takes a 9x9 numpy array as input and checks whether it is a valid sudoku entry. Your function should output True or False based on the validity.

In [22]:

def check_sudoku(grid):
    for row in range(len(grid)):
        for col in range(len(grid)):
            if grid[row][col] < 1 :
                return False
            # check value is within 1 through n.
            # for example a 2x2 grid should not have the value 8 in it
            elif grid[row][col] > 9:
                return False
    # check the sub-matrix
    for i in  range (0,8,3):
        for j in range (0,8,3):
            x = grid [i:i+3,j:j+3]
            y = x.reshape((1,9))
            print(x)
            for row in y:
                if sorted(list(set(row))) != sorted(row):
                    return False
    # check the rows
    for row in grid:
        if sorted(list(set(row))) != sorted(row):
            return False
    # check the cols
    cols = []
    for col in range(len(grid)):
        for row in grid:
            cols += [row[col]]
        # set will get unique values, its converted to list so you can compare
        # it's sorted so the comparison is done correctly.
        if sorted(list(set(cols))) != sorted(cols):
            return False
        cols = []

    # if you get past all the false checks return True
    return True
import numpy as np
z = np.random.randint(1,9, size=(9, 9))
a = np.array ([[8,4,9,5,2,1,7,3,6],
              [2,5,7,8,6,3,9,1,4],
              [1,6,3,7,4,9,2,5,8],
              [3,2,5,1,9,6,4,8,7],
              [4,9,8,3,5,7,6,2,1],
              [7,1,6,4,8,2,3,9,5],
              [9,8,4,2,7,5,1,6,3],
              [6,7,1,9,3,8,5,4,2],
              [5,3,2,6,1,4,8,7,9]])
print (z)
check_sudoku(z)


[[3 6 2 8 3 6 2 8 8]
 [6 8 7 1 2 1 6 6 5]
 [8 6 4 4 5 2 8 5 7]
 [6 5 4 6 8 4 8 4 3]
 [3 5 6 2 7 7 5 5 3]
 [2 4 3 3 3 6 3 6 6]
 [6 5 4 2 3 1 2 7 6]
 [5 5 7 6 1 5 4 6 3]
 [8 4 7 7 2 3 5 1 7]]
[[3 6 2]
 [6 8 7]
 [8 6 4]]


False

In [ ]:
z = np.random.randint(1,9, size=(9, 9))
check_sudoku(z)

# 3. Edit distance (Levenstein distance)
Write a function that takes two strings as input and calculates the edit distance between the two strings. 
Edit distance between "cat" and "cut" is 1
You can refer to the algorithm here - https://en.wikipedia.org/wiki/Edit_distance

In [2]:
def Levensteindistance(Inputstring,outputstring):

    count=0 #initialise counter as zero
# if two strings are equal in length then we only need to make substitutions to make changes to the string
    
    if len(Inputstring)==len(outputstring):
        for i in range(len(Inputstring)):
            if Inputstring[i]!=outputstring[i]:
                count=count+1
# if length of one string is either greater than or less than the other string then we need to make substitutions as well as addition or deletions as per the case    
   
    elif len(outputstring)>len(Inputstring):
        for i in range(len(Inputstring)):
            if outputstring[i]!=Inputstring[i]:
                count=count+1
        count=count+len(outputstring)-len(Inputstring)

    elif len(outputstring)<len(Inputstring):
        for i in range(len(outputstring)):
            if outputstring[i]!=Inputstring[i]:
                count=count+1
        count=count+len(Inputstring)-len(outputstring)

    return count


In [3]:
Levensteindistance(Inputstring="python",outputstring="java")

6

# 4. Parentheses check
Write a function that takes an expression as input and checks whether the parentheses are balanced. 
{ ( ( [ ] ) ) } is a valid expression.
{ { ( } ) } }, { ( }, { ] are not valid expressions. 
Your function should output True or False based on the validity of the expression

In [27]:
def paranthesescheck(inputstring):
    para_dict={'{':'}','[':']','(':')'} #first creating a dictionary containing pairwise parantheses
    closing = para_dict.values() 

    my_list = []
    for characters in inputstring:
        presentkeys = para_dict.get(characters, None) # checking if any characters in string match with the defined key
        if presentkeys:
            my_list.append(presentkeys)# putting the values corresponding to these keys into my_list
        elif characters in closing:
            if not my_list or characters != my_list.pop():
                return False
    return not my_list


In [28]:
paranthesescheck("{{this is a string}}()()[[]]")

True

# 5. Palindrome check 
a. Write a function that checks whether a string is a palindrome. "Anna" is a palindrome.
b. Write a function that takes a string as an input and checks whether any anagram of the string is a palindrome.
Hint: You do not need to generate all the anagrams. In both cases your function should output True or Flase.

In [13]:
def Palindrome_Check (String):
    countt = 0
    i = 0 # initiated to approach string from left end
    j = len(String)-1 #simulataneously approach from right end
    while (i <= j):
        if ( String[i] == String[j]):
            countt = countt +1 #increment count each time encounter same value
        i=i+1
        j=j-1
    if(countt == ((len(String)//2)+(len(String)%2))): #when count becomes equal to number steps it moved before i=j
        return True
    else:
        return False



def Anagram_Check (Strings):
    from itertools import permutations
    Anags = [''.join(p) for p in permutations(Strings)] #permute all the letters of the strings and then join them to make different strings
    count = 0
    for i in range(len(Anags)): # extracting strings and parsing them to palindrome function
        Palin = Anags[i]
        print (Palin , "is a palindrome" , Palindrome_Check (Palin))
        if(Palindrome_Check (Palin)):
            count = count+1
    if(count > 0):
        return True
    else:
        return False



    

In [15]:
Anagram_Check ("pop")


pop is a palindrome True
ppo is a palindrome False
opp is a palindrome False
opp is a palindrome False
ppo is a palindrome False
pop is a palindrome True


True

# 6. Prime factorization
Write a function that takes into input a number and outputs all the prime factors of the number. Your function should output a dictionary with all the prime factors as keys and their corresponding orders as values.
9 -> {3:2}
12 -> {2:2, 3:1}

In [29]:
def prime_factors(n):
    
    factors =[]
    if n > 1:
        i = 2
        while n % i != 0: #append i in list untill remainder is 0 and increment i when remainder is 0
            i += 1
        factors.append(i)
        factors.extend(prime_factors(n / i)) # using recursive calling of function
    return factors
    

def primefactorsdict(n): # defining a function to add elements from list to dictionary
    fac_list=[]
    fac_list=prime_factors(n)
    pf_dict={}
    for k in range(len(fac_list)):
        pf_dict[fac_list[k]]=fac_list.count(fac_list[k]) # counting repeated values and putting them as values of keys(prime numbers)

    return pf_dict


In [30]:
primefactorsdict(1000)



{2: 3, 5: 3}